# You can make apps auto-start here
# Relevant Hyprland wiki section: https://wiki.hyprland.org/Configuring/Keywords/#executing
exec-once = wl-gammarelay-rs
exec-once = hyprshade on vibrance
exec-once = busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Temperature q 2700
exec-once = busctl --user set-property rs.wl-gammarelay / rs.wl.gammarelay Gamma d 1
