# See https://wiki.hyprland.org/Configuring/Binds/
#!
##! User
bind = Ctrl+Super, Slash, exec, xdg-open ~/.config/illogical-impulse/config.json # Edit shell config
bind = Ctrl+Super+Alt, Slash, exec, xdg-open ~/.config/hypr/custom/keybinds.conf # Edit extra keybinds

binde = Super SHIFT, left, resizeactive,-25 0
binde = Super SHIFT, right, resizeactive,25 0
binde = Super SHIFT, up, resizeactive,0 -25
binde = Super SHIFT, down, resizeactive,0 25

bind = Super Alt, left, movewindow, l
bind = Super Alt, right, movewindow, r
bind = Super Alt, up, movewindow, u
bind = Super Alt, down, movewindow, d

bind = Super SHIFT, U, movetoworkspace, special
bind = Super, U, togglespecialworkspace,

bind = Super+Alt, N, global, quickshell:barToggle # [hidden]
# Add stuff here
# Use #! to add an extra column on the cheatsheet
# Use ##! to add a section in that column
# Add a comment after a bind to add a description, like above
bind = Super SHIFT, I, togglesplit
bind = Super, P, pseudo

bind = Super+SHIFT, Q, exec, hyprctl dispatch exit
