# Initialize TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'wfxr/tmux-power'
# set -g @plugin 'erikw/tmux-powerline'  # Comment out to avoid conflicts

# Your custom settings
unbind C-Space
set -g prefix C-Space
bind C-Space send-prefix
set -g mouse on
set-option -g history-limit 5000

bind-key "|" split-window -h -c "#{pane_current_path}"
bind-key "\\" split-window -fh -c "#{pane_current_path}"
bind-key "-" split-window -v -c "#{pane_current_path}"
bind-key "_" split-window -fv -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind Space last-window
bind-key C-Space switch-client -l

# Theme settings for tmux-power
set -g @tmux_power_theme 'everforest'
set -g @tmux_power_date_format '%F'
set -g @tmux_power_time_format '%T'

# Run TPM
run '~/.tmux/plugins/tpm/tpm'
