#!/bin/bash

THEME="Orchis-Dark-Compact"
ICON="tokyo-night"
FONT="BalsamiqSans"
CURSOR="Bibata-Modern-Ice-Extra-Large-Windows"

gsettings set org.gnome.desktop.interface gtk-theme "$THEME"
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface font-name "$FONT"
gsettings set org.gnome.desktop.interface icon-theme "$ICON"
gsettings set org.gnome.desktop.interface cursor-theme "$CURSOR"
