#!/bin/bash

THEME="Graphite-orange-Dark"
ICON="Infinity-Dark-Icons"
FONT="Balsamiq Sans 14"
CURSOR="Fuchsia"

gsettings set org.gnome.desktop.interface gtk-theme "$THEME"
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
gsettings set org.gnome.desktop.interface font-name "$FONT"
gsettings set org.gnome.desktop.interface icon-theme "$ICON"
gsettings set org.gnome.desktop.interface cursor-theme "$CURSOR"
